### ISSUE TITLE
Implement: auth init

### ISSUE THREAD

**Issue by mwvaughn** [TACC-Cloud/tapis-cli-ng#171]
Add a "auth init" command to tapis-cli

**Comment by mwvaughn** [comment]
Completed 15d63e414e612ab32efe19dde10e63e0ae313c38

**Comment by JoshuaUrrutia** [comment]
Specifying all the options generates some warnings and requires a redundant keyboard interaction:
```
# tapis auth init --tenant-id tacc.prod --username urrutia --password xxxx
Tenant changed. Username and password must be specified.
Username changed. Password must be specified.
Username [urrutia]: 
```
Which then goes through fine if you hit the return key, but I wouldn't expect that to be necessary.
