### ISSUE TITLE
Tapis command errors do not return all relevant details

### ISSUE THREAD

**Issue by mwvaughn** [TACC-Cloud/tapis-cli-ng#226]
Errors from the Tapis services return the reason for errors, but the CLI does not return the plaintext explanations, only the HTTP error code + server message. One good example is trying to send an apps definition with invalid keys.

**Comment by mwvaughn** [comment]
This has been updated in AgavePy, but still needs to be implemented in the Tapis CLI `TaccApiDirectClient` class

**Comment by mwvaughn** [comment]
This should be fixed in ef02c3742ff6c403c19b84fc9b44cb01b44fc0cf

**Comment by JoshuaUrrutia** [comment]
Working for me, ex:
```
urrutia$ tapis apps create -F test_app.json 
[Errno 400] Bad Request for https://api.sd2e.org/apps/v2/: 'Invalid executionSystem value, hpc-tacc-wrangler-urruti. Please specify a valid system id representing an execution system on which this app should run.'
```

**Comment by mwvaughn** [comment]
Splendid!
