### ISSUE TITLE
tapis systems create: better SSH Key support

### ISSUE THREAD

**Issue by johnfonner** [TACC-Cloud/tapis-cli-ng#230]
**Is your feature request related to a problem? Please describe.**
Formatting SSH Keys correctly inside of JSON is not intuitive, and can cause users to encounter authentication errors for a newly made system that are difficult to resolve.

**Describe the solution you'd like**
Provide some sort of formatting or templating support to insert a key pair into a JSON file.  This could be a separate command such as "keys format", "systems template", or just an additional argument to systems create.

**Comment by mwvaughn** [comment]
Thanks! Scoping this to a near-future release as I have been thinking along the same lines.
