### ISSUE TITLE
Implement: settings set

### ISSUE THREAD

**Issue by mwvaughn** [TACC-Cloud/tapis-cli-ng#233]
Add a "settings set" command to tapis-cli

**Comment by JoshuaUrrutia** [comment]
Tested with:
```
tapis settings set TAPIS_CLI_PAGE_SIZE 24
```
Which resets the page size variable in my .env file. I did notice it puts quotes around the variable, in the .env file:
```
TAPIS_CLI_PAGE_SIZE="24"
```
Whereas before I had the variable set without the quotes in my .env file:
```
TAPIS_CLI_PAGE_SIZE=24
```
The quotes aren't duplicated (or removed) if I run:
```
tapis settings set TAPIS_CLI_PAGE_SIZE "24"
```

It doesn't seem to cause any issues but I thought it was worth pointing out.

**Comment by mwvaughn** [comment]
This should be fine, so I am going to close the issue.
