### ISSUE TITLE
Command tapis jobs outputs list fails w a rendering error

### ISSUE THREAD

**Issue by mwvaughn** [TACC-Cloud/tapis-cli-ng#236]
**Describe the bug**
`tapis jobs outputs list <job_uuid>` fails with the following error: 

`"lastModified": Object of type 'datetime' is not JSON serializable`

**Expected behavior**

CLI responses should always display either a humanized or ISO date string for `lastModified`

**Comment by mwvaughn** [comment]
This appears to be a generalized issue, since `tapis files list -v` fails, too.

**Comment by JoshuaUrrutia** [comment]
Tested the default and the all the `-f $FORMAT` options all are working as expected w/ human readable lastModified dates.
