### ISSUE TITLE
`tapis files move` requires full path, but should default to filename like `tapis files copy`

### ISSUE THREAD

**Issue by rstijerina** [TACC-Cloud/tapis-cli-ng#238]
**Describe the bug**
```tapis files move <agave_uri> <destinanation>``` requires that a filename be specified in the destination, whereas ```tapis files copy  <agave_uri> <destinanation>``` does not.

**To Reproduce**
1. Works: `tapis files copy agave://frontera.sal.storage/test.tar.gz tapis-cli-ng-test`

> +--------------+---------------------------------------+
> | Field        | Value                                 |
> +--------------+---------------------------------------+
> | name         | tapis-cli-ng-test                     |
> | uuid         | 2264561570391658986-242ac112-0001-002 |
> | owner        | sal                                   |
> | path         | /tapis-cli-ng-test                    |
> | lastModified | 2019-11-14T16:57:25.000-06:00         |
> | source       | None                                  |
> | status       | STAGING_COMPLETED                     |
> | nativeFormat | dir                                   |
> | systemId     | frontera.sal.storage                  |
> +--------------+---------------------------------------+

2. Does **not** work: ```$ tapis files move agave://frontera.sal.storage/test.tar.gz tapis-cli-ng-test```

> ```[Errno 400] Bad Request for https://api.tacc.utexas.edu/files/v2/media/system/frontera.sal.storage//test.tar.gz: 'Folder at tapis-cli-ng-test already exists'```

3. Works: ` tapis files move "agave://frontera.sal.storage/test.tar.gz" "tapis-cli-ng-test/test.tar.gz"`

> +--------------+---------------------------------------+
> | Field        | Value                                 |
> +--------------+---------------------------------------+
> | name         | test.tar.gz                           |
> | uuid         | 8405087927074492906-242ac112-0001-002 |
> | owner        | sal                                   |
> | path         | /tapis-cli-ng-test/test.tar.gz        |
> | lastModified | 2019-11-14T17:06:57.018-06:00         |
> | source       |                                       |
> | status       | STAGING_COMPLETED                     |
> | nativeFormat | raw                                   |
> | systemId     | frontera.sal.storage                  |
> +--------------+---------------------------------------+

**Expected behavior**
A `tapis files move` command should default to the filename of the object being moved.

**Screenshots**

**Desktop (please complete the following information):**
 - tapis-cli docker container: `tacc/tapis-cli-ng:latest`

**Comment by mwvaughn** [comment]
I'm thinking this one through. Thanks for the feedback!

**Comment by mwvaughn** [comment]
@rstijerina any more feedback on this? If not, I will close the issue as part of the release process on Friday.

**Comment by rstijerina** [comment]
No more comments as of now - thanks!

**Comment by mwvaughn** [comment]
Closing, but am happy to revisit this again after release.
