### ISSUE TITLE
Abaco CLI syntax design

### ISSUE THREAD

**Issue by mwvaughn** [TACC-Cloud/tapis-cli-ng#248]
In this thread, we will design and discuss the command syntax for the Python version of the Abaco CLI.

**Comment by mwvaughn** [comment]
For reference, here is the current Bash CLI help

```
abaco -h

Usage: abaco [COMMAND] [OPTION]...

Set of commands for interacting with Abaco API. Options vary by
command; use -h flag after command to view usage details.

Commands:
  list, ls, actors, images	list actors
  create, make, register        create new actor
  delete, remove, rm            remove actor
  update, change                update base Docker image
  permissions, share            list and update actor permissions
  workers, worker               view and add workers
  submit, run                   run actor
  executions                    view actor executions
  messages, mailbox             count (or purge) an actor's messages
  logs				view execution logs
  init                          create a new actor project
  deploy                        build and deploy an actor
  version                       report CLI and service versions
  aliases, alias                manage aliases for actors


GitHub Issues:
  https://github.com/TACC-Cloud/abaco-cli/issues

Documentation:
  Abaco: https://abaco.readthedocs.io/en/latest/

Help:
  support@tacc.cloud
```

**Comment by mwvaughn** [comment]
I will start:

| Bash                     | Python                            | Notes |
|--------------------------|-----------------------------------|-------|
| `abaco ls`               | `tapis actors list`               |       |
| `abaco ls <ACTOR,ALIAS>` | `tapis actors show <ACTOR,ALIAS>` |       |

**Comment by shwetagopaul92** [comment]
|                            Bash                                        |                              Python                                        |   Notes    |                                                 
|-------------------------------------------- |-------------------------------------------------|----------|
| `abaco ls`                                                         | `tapis actors list`                                                    |                |                           
|  `abaco ls <ACTOR,ALIAS>`                           | `tapis actors show <ACTOR,ALIAS>`                   |                |    
| `abaco images <ACTORS,ALIAS>`                | `tapis actors images <ACTOR,ALIAS>`                |                |
| `abaco create  <IMAGE>`                                | `tapis actors create <IMAGE>`                             |                |
| `abaco make`                                                    | `tapis actors make`                                               |                |
| `abaco register`                                                | `tapis actors register`                                           |                |                                           
| `abaco delete <ACTORID>`                             | `tapis actors delete <ACTORID>`                        |                |                  
|  `abaco rm`                                                       | `tapis actors rm`                                                    |                                           
| `abaco update <ACTOR,ALIAS> <IMAGE>`  | `tapis actors update <ACTOR,ALIAS><IMAGE>`  |     |
| `abaco change <ACTOR,ALIAS> <IMAGE>` | `tapis actors change <ACTOR,ALIAS><IMAGE>`  |     |
| `abaco permissions <ACTORID>`                 | `tapis actors permissions <ACTORID>`                  |      |
|` abaco share <ACTORID>`                            | `tapis actors share <ACTORID>` .                           |         |
|` abaco workers <ACTORID>`                        | `tapis actors workers <ACTORID>`                         |           |

**Comment by mwvaughn** [comment]
Good start! Let's iterate a bit.

**Comment by mwvaughn** [comment]
We only want one of the synonyms for each verb. So, let's strike out the following:

* `tapis actors images`
* `tapis actors make`
* `tapis actors register`
* `tapis actors rm`
* `tapis actors change`
* `tapis actors mailbox`

**Comment by mwvaughn** [comment]
Because aliases are standalone entities, we need to continue having them as a top-level entity. So, we can't do `tapis actors aliases *`

**Comment by mwvaughn** [comment]
The actions `submit` and `run` used to be just synonyms for sending a message to an actor's mailbox. With the advent of synchronous executions, what if we did something like:

* `tapis actors submit` sends a message for async execution. It is analogous to `tapis jobs submit`
* `tapis actors run` also sends a message but as a synchronous execution.

**Comment by mwvaughn** [comment]
For worker management, we only want `workers` even if the subject is singular. We tried doing apps/app, jobs/job etc with the Tapis part of the CLI and it caused some distress. We also want to map out worker management features that are not in the current CLI. Here's a suggestion:

* `tapis actors workers list <ACTOR_ID>`
* `tapis actors workers show <ACTOR_ID> <WORKER_ID>`
* `tapis actors workers create <ACTOR_ID>` - add one worker
* `tapis actors workers delete <ACTOR_ID> <WORKER_ID>` - delete a worker

**Comment by mwvaughn** [comment]
For executions, we also only want a single form. I also propose moving the logs command under it. 

* `tapis actors executions list <ACTOR_ID>`
* `tapis actors executions show <ACTOR_ID> <EXEC_ID>`
* `tapis actors executions logs <ACTOR_ID> <EXEC_ID>`
* `tapis actors executions stop <ACTOR_ID> <EXEC_ID>` - stops a pending execution, which is possible in the API but not CLI

No support for `create`, `update`, or `delete` exists in the API nor is it planned.

**Comment by mwvaughn** [comment]
For permissions, we've settled into using `pems` in the rest of the CLI. We've attempt to implement list, show, grant, revoke, and drop for each instance. For Abaco that could look like:

* `tapis actors pems list <ACTOR_ID>`
* `tapis actors pems show <ACTOR_ID> <USERNAME>` - get permission for a specific user
* `tapis actors pems grant <ACTOR_ID> <USERNAME> <PERMISSION>`
* `tapis actors pems revoke <ACTOR_ID> <USERNAME> <PERMISSION>`
* `tapis actors pems drop <ACTOR_ID>`

**Comment by mwvaughn** [comment]
Good catch for `abaco version` but we don't need it any longer. The general `tapis info versions` command will fetch and return the Abaco platform version.

**Comment by mwvaughn** [comment]
This brings us to the core actors management workflow. 

* `tapis actors list`
* `tapis actors show <ACTOR_ID>`
* `tapis actors create`
* `tapis actors update <ACTOR_ID>`
* `tapis actors delete <ACTOR_ID>`

This should align with to the Tapis API commands.

**Comment by mwvaughn** [comment]
Aliases are tricky. Our existing CLI has made it seem like they're a top-level API, but really they are a child endpoint for actors. Thus, I suggest the following:

* `tapis actors aliases list` show all known aliases
* `tapis actors aliases show <ALIAS>` show one specific alias
* `tapis actors aliases create <ALIAS> <ACTOR_ID>` create a new alias
* `tapis actors aliases update <ALIAS> <ACTOR_ID>` **NOT SUPPORTED BY API** (we could wrap a delete and create workflow if we wanted to)
* `tapis actors aliases delete <ALIAS>` delete an alias

**Comment by mwvaughn** [comment]
We've got the projects workflow right above. It's the same as for `tapis apps *`:

* `tapis actors init` to create a new Actor project
* `tapis actors deploy` to deploy from an extant Actor project

**Comment by mwvaughn** [comment]
We forgot all about **nonces** since they are not implemented in the Bash CLI at present!

**Comment by mwvaughn** [comment]
> For executions, we also only want a single form. I also propose moving the logs command under it.
> 
> * `tapis actors executions list <ACTOR_ID>`
> * `tapis actors executions show <ACTOR_ID> <EXEC_ID>`
> * `tapis actors executions logs <ACTOR_ID> <EXEC_ID>`
> * `tapis actors executions stop <ACTOR_ID> <EXEC_ID>` - stops a pending execution, which is possible in the API but not CLI
> 
> No support for `create`, `update`, or `delete` exists in the API nor is it planned.
> 
> Thought a bit about substituting `exec` for `executions` to be more typist-friendly, but `exec` is a very common Bash command and I can't see the benefit in making it possible to accidentally run it while scripting using the CLI.

1/14/2020: We decided to try calling them `execs` in lieu of `executions`
