### ISSUE TITLE
Implement handling for Tapis URI in postits

### ISSUE THREAD

**Issue by wjallen** [TACC-Cloud/tapis-cli-ng#311]
Tapis CLI users will be used to working in Tapis URI space. However, when I go to create a postit for a file in my storage system, I have to figure out what the URL is. E.g.:

```
   $ tapis postits create https://api.tacc.utexas.edu/files/v2/media/system/utrc-home.wallen/test_folder/file.txt
```

What I'd like to be able to do instead is:

```
   $ tapis postits create agave://utrc-home.wallen/test_folder/file.txt
```

**Comment by mwvaughn** [comment]
Great suggestion!
