### ISSUE TITLE
Allow user to specify public/private keys from file during systems create/update

### ISSUE THREAD

**Issue by mwvaughn** [TACC-Cloud/tapis-cli-ng#315]
**Is your feature request related to a problem? Please describe.**

The current workflow for creating or updating a system with SSH/SFTP authentication requires one to serialize and store their public and private SSH keys and embed them in a JSON file. This is pretty annoying and might lead to leakage of a user's keys if that JSON file got committed to a git repo. 

**Describe the solution you'd like**

Add arguments to `systems create` and `systems update` to specify private key for login and storage. Possibly, there could be a CLI config for default SSH key that could be read from. 

The precedence order would be:

1. Value provided on the CLI
2. Value provided in the JSON file
3. Value provided via the CLI config

**Comment by wjallen** [comment]
YES
